### PR TITLE
"cmd.exe /c start" is not a command

### PR DESCRIPTION
**Pull request by mattn**
must be slice. Do you prefer `opnr.cmdArgsFor(url)`?

### CODE REVIEW

**Comment by romanyx** [comment]
Thanks! No, I think it's ok like it is for now.

**Comment by romanyx** [comment]
Can you please help me with vim command? I'm trying to create command to call `mdopen` on file I'm editing by `:MDOpen`. I'm tried to write command at `.vimrc` but it's not working. Something like:

```
command! MDOpen execute 'mdopen' expand('%:p')
```

**Comment by mattn** [comment]
You can put below into your vimrc

```
augroup MDOpen
  au!
  autocmd FileType markdown command! -buffer MDOpen silent !mdopen %
augroup END
```

Or put following file into your ~/.vim/ftplugin/markdown/mdopen.vim

```
command! -buffer MDOpen silent !mdopen %
```

**Comment by romanyx** [comment]
Cool, thanks a lot!

**Pull request merged**
